### ISSUE TITLE
react-native-aliyun-push is dependency or not?

### ISSUE THREAD

**Issue by EsrefDurna** [wonday/react-native-live-stream#2]
the readme  says drag "react-native-aliyun-push" etc into xcode however its not in this npm modules dependency.

please clearify the readme or add react-native-aliyun-push into the dependency.
and i believe the after installation instruction should show some screenshots.

**Comment by wonday** [comment]
Sorry , readme copy from my other project...
It does not need dependent on "react-native-aliyun-push".
I am fixing it now.
