### ISSUE TITLE
Problem using Youtube

### ISSUE THREAD

**Issue by chrismpalmer** [wonday/react-native-live-stream#3]
Hello!

I am having a problem getting this working with youtube ? Since it exposes a standard rtmp end point I thought it would work but its just sitting there.

`
                <LivePlayer source={{uri:'rtmp://a.rtmp.youtube.com/live2/FOO-KEY'}}
                    ref={(ref) => {
                        this.player = ref
                    }}
                    style={livestyle.video}
                    paused={false}
                    muted={false}
                    bufferTime={300}
                    maxBufferTime={1000}
                    resizeMode={"contain"}
                    onLoading={()=>{ console.log('loading...')}}
                    onLoad={()=>{ console.log('onLoad')}}
                    onEnd={()=>{}}
                    />
                </View>
`

**Comment by wonday** [comment]
It should support it, if you can play it by other player, like [OBS-Studio](https://obsproject.com/download).
I can not access youtube, so I can not test it.

**Comment by chrismpalmer** [comment]
I can start a stream with obs no problem. I will check the url, I did step
through the c code and seems like it is attempting to connect continously.


On Mar 25, 2019 at 6:56 PM, <wonday <notifications@github.com>> wrote:

It should support it, if you can play it by other player, like OBS-Studio
<https://obsproject.com/download>.
I can not access youtube, so I can not test it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wonday/react-native-live-stream/issues/3#issuecomment-476443541>,
or mute the thread
