### ISSUE TITLE
npmjs.com page has wrong information

### ISSUE THREAD

**Issue by yehancha** [wonday/react-native-live-stream#7]
Information at [https://www.npmjs.com/package/react-native-live-stream](https://www.npmjs.com/package/react-native-live-stream) is wrong.

1. npm/yarn information is about react-native-orientation-locker. It should be about react-native-live-stream.
2. iOS framework integration is about react-native-aliyun-push. It should be about react-native-live-stream.
3. yarn is misspelled as yard.

**Comment by wonday** [comment]
I had updated it at v1.0.1
