### ISSUE TITLE
Duplicate symbol issues with BoringSSL-GRPC

### ISSUE THREAD

**Issue by yehancha** [wonday/react-native-live-stream#8]
I'm getting this error while building the iOS project with react-native-live-stream.
```
duplicate symbol _md5_block_data_order in:
    /Users/yehancha/Documents/musing-mobile/node_modules/react-native-live-stream/ios/libs/NodeMediaClient.framework/NodeMediaClient(md5_dgst.o)
    /Users/yehancha/Library/Developer/Xcode/DerivedData/musing-enzttvuorxmrncgxytndapfqbokv/Build/Products/Debug-iphoneos/BoringSSL-GRPC/libBoringSSL-GRPC.a(md5.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
What can I do to resolve this issue?

**Comment by wonday** [comment]
I do not know,  
It is related with iOS development,
You can google it.

**Comment by yehancha** [comment]
It says the solution is to use a different symbol in one project so there will be no duplicates. You may consider this in future releases so react-native-live-stream can be used with BoringSSL-GRPC.

Thanks for the attention.

**Comment by cristian-milea** [comment]
@yehancha did you find a solution? I'm having the same problem and I've destroyed google searching for answers

my project is on react native 0.59.9

**Comment by yehancha** [comment]
@cristian-milea, sorry I don't remember actually what happened after this since it is a long time. By the way, when I was checking my package.json, I have used https://www.npmjs.com/package/react-native-video. Hope this will help you.
